# Generated by Django 2.2.1 on 2019-05-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
