# Generated by Django 2.2.1 on 2019-06-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
