# Generated by Django 2.2.1 on 2019-06-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20190612_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(default='0'),
        ),
    ]
